# 사이트 설정 (사이트 구성)
title: '달이 차면 기울어요'
description: '달차기'
keywords: 'AI, Unity'
url: 'https://kickthemoon0817.github.io/' # 호스트 URL

# 네비게이션 (한국어 문자 공백: &emsp;)
nav:
  Home: '/'
  Tag: '/tags.html'
  Timeline: '/timeline.html'
  aboutMe: '/about.html'
  Links: '/friendLink.html'

# 블로거 정보
author: true
name: 'Sungmin Kim'
NickName: 'Kickthemoon'
webtitle: 'Kick The Moon'
bio: '-ing'
about: true
aboutyou: 'studying about AI, ...'
portraits: '/assets/profile.jpeg' # 프로필 이미지 파일 경로

# 소셜 네트워크 서비스 (SNS)
SNS: true
SNS-icon: # ['Facebook', 'github', 'Twitter', 'instagram']
  mail: 'kickthemoon0817@gmail.com'
  github: 'kickthemoon0817'
  instagram: 'kickthemoon0817'
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: 'kickthemoon0817@gmail.com'

# 페이지 나누기 설정
paginate: 2
paginatepath: ['page:num']

# 시작년도
footer:
  since: 2024

# Markdown 설정
markdown: kramdown
kramdown:
  input: GFM
# 코드 하이라이팅 (rouge 사용)
highlighter: rouge
# 코드 하이라이팅 테마 (pygments 테마 선택: autumn, default, emacs, friendly, manni, murphy, pastie, perldoc, tango 중 선택)
pygmentsTheme: 'default'

# 친구 링크
friends:
  jekyll: 'https://www.jekyll.com/'

# 댓글 시스템 (최적의 경험을 위해 Disqus, Livere, Gitment 중 하나를 선택)
# Disqus 댓글
disqus: false
disqus_url: '' # 예: https://abc.disqus.com/embed.js

# Livere 댓글
livere: false
livere_uid: '' # 예: MTAyMC8zNDI2OS8xMDgwNg==

# Gitment 댓글 (GitHub 기반 댓글 시스템)
Gitment: true
Gitment_owner: 'your-github-username'  # GitHub 사용자명 입력
Gitment_repo: 'your-blog-repo'         # GitHub 블로그 저장소명 입력
client_id: 'your-oauth-client-id'        # OAuth Application 등록 후 받은 client_id 입력
client_secret: 'your-oauth-client-secret'  # OAuth Application 등록 후 받은 client_secret 입력

# 공유 (Share) : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['twitter', 'facebook']

# 바이두 통계 (자신의 바이두 관련 코드 입력)
baidu: false
baidu-url: ''

# 구글 분석 (자신의 구글 분석 추적 ID 입력)
google: false
google-ID: ''

# 블로그 헤더 대체 색상 (포스트 헤더의 색상 변수로 사용)
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
